# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mondais',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('kaisetu', models.TextField()),
                ('seikai', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shitumons',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('shitumon', models.TextField()),
                ('kaitou', models.TextField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('mondai_id', models.ForeignKey(db_column='mondai_id', on_delete=django.db.models.deletion.CASCADE, to='sui_hei.Mondais')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='shitumons',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='sui_hei.Users'),
        ),
        migrations.AddField(
            model_name='mondais',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='sui_hei.Users'),
        ),
        migrations.AddField(
            model_name='chats',
            name='mondai_id',
            field=models.ForeignKey(db_column='mondai_id', on_delete=django.db.models.deletion.CASCADE, to='sui_hei.Mondais'),
        ),
        migrations.AddField(
            model_name='chats',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='sui_hei.Users'),
        ),
    ]
